-- Lascivious Factions System - client UI localization.
-- Values live in Translate/*/UI.json so PZ loads the UI_LFS_* category and
-- creates proper Unicode Java strings.  EN intentionally mirrors PTBR: this
-- server's version always presents the LFS interface in Brazilian Portuguese.
require "LFS_Shared"
local FF = LasciviousFactionsSystem
local KEYS = {
    ["%s declined your application."] = "UI_LFS_778943116",
    ["%s has applied to join your faction."] = "UI_LFS_827482483",
    ["%s has joined your faction."] = "UI_LFS_494815457",
    ["%s marked as an enemy."] = "UI_LFS_539083603",
    ["%s wants to form an alliance."] = "UI_LFS_1132630292",
    ["A line about yourself (optional)"] = "UI_LFS_1751439053",
    ["A role with that name already exists."] = "UI_LFS_939786792",
    ["ALLY"] = "UI_LFS_2088894873",
    ["Abandon raid"] = "UI_LFS_102041407",
    ["Accent colour"] = "UI_LFS_863907542",
    ["Accept"] = "UI_LFS_649454138",
    ["Add"] = "UI_LFS_193451182",
    ["Advertise for members"] = "UI_LFS_2012778561",
    ["All factions"] = "UI_LFS_2042922454",
    ["Alliance request declined."] = "UI_LFS_1205468553",
    ["Alliance request sent to %s."] = "UI_LFS_1979462979",
    ["Alliance with %s ended."] = "UI_LFS_342109565",
    ["Allies"] = "UI_LFS_660454852",
    ["Allies can build & craft in our claims"] = "UI_LFS_1163904074",
    ["Allies can build/craft here"] = "UI_LFS_1154373554",
    ["Allies can destroy & move objects in our claims"] = "UI_LFS_1626261998",
    ["Allies can destroy/move here"] = "UI_LFS_53611623",
    ["Allies, pacts & wars"] = "UI_LFS_1971378569",
    ["Allow PvP between members"] = "UI_LFS_967710135",
    ["Allowed"] = "UI_LFS_320408508",
    ["An admin removed one of your faction's claimed areas."] = "UI_LFS_1654334611",
    ["Applicants"] = "UI_LFS_1780914013",
    ["Application from %s declined."] = "UI_LFS_1989944240",
    ["Application sent to %s."] = "UI_LFS_1922270137",
    ["Application to %s withdrawn."] = "UI_LFS_1329516939",
    ["Applied"] = "UI_LFS_481570707",
    ["Apply"] = "UI_LFS_215387789",
    ["Area Access"] = "UI_LFS_1280663905",
    ["Attackers vs defenders"] = "UI_LFS_1655648055",
    ["BEST SKILLS"] = "UI_LFS_334924824",
    ["Blocked"] = "UI_LFS_1614989928",
    ["Browsing"] = "UI_LFS_937944027",
    ["Build & craft"] = "UI_LFS_377893285",
    ["Build in claims"] = "UI_LFS_29571113",
    ["CLAIM ACCESS FOR ALLIES"] = "UI_LFS_704727026",
    ["CLAIM SIZE"] = "UI_LFS_1683657012",
    ["Can build & craft here"] = "UI_LFS_1480312719",
    ["Can destroy & move objects here"] = "UI_LFS_1073283350",
    ["Can loot containers here"] = "UI_LFS_400733135",
    ["Can manage members"] = "UI_LFS_604050493",
    ["Cancel"] = "UI_LFS_725745840",
    ["Claim & unclaim land"] = "UI_LFS_1852232199",
    ["Claim cleared."] = "UI_LFS_1511003306",
    ["Claim rejected: %s"] = "UI_LFS_1019237144",
    ["Claim set (%s tiles)."] = "UI_LFS_1480391215",
    ["Claiming land"] = "UI_LFS_1443491818",
    ["Claims"] = "UI_LFS_738330595",
    ["Clear"] = "UI_LFS_217603534",
    ["Close"] = "UI_LFS_217615005",
    ["Create"] = "UI_LFS_745581374",
    ["Create Faction"] = "UI_LFS_545412578",
    ["Create faction"] = "UI_LFS_1070198293",
    ["Declare raids"] = "UI_LFS_234953624",
    ["Decline"] = "UI_LFS_1762584969",
    ["Delete role"] = "UI_LFS_432970545",
    ["Description"] = "UI_LFS_1706748719",
    ["Description (shown on entry)"] = "UI_LFS_837120347",
    ["Description (shown when players enter your claim)"] = "UI_LFS_726171225",
    ["Destroy & move"] = "UI_LFS_1167308377",
    ["Directory"] = "UI_LFS_191048448",
    ["Disband faction"] = "UI_LFS_549338184",
    ["Drag out the area..."] = "UI_LFS_1822579212",
    ["Draw claim"] = "UI_LFS_736266912",
    ["Drawing..."] = "UI_LFS_1458474851",
    ["Duration"] = "UI_LFS_2093756255",
    ["ENEMY"] = "UI_LFS_218861733",
    ["End raid (admin)"] = "UI_LFS_561378884",
    ["Ends in"] = "UI_LFS_1260145655",
    ["Entry banner"] = "UI_LFS_937490363",
    ["Erase"] = "UI_LFS_220187223",
    ["Erasing..."] = "UI_LFS_655393258",
    ["Everyone, including factions we are at war with."] = "UI_LFS_1875239778",
    ["FACTION SCORE"] = "UI_LFS_1094389816",
    ["FACTIONS"] = "UI_LFS_1138083480",
    ["FACTIONS RECRUITING"] = "UI_LFS_602017218",
    ["Faction created: %s"] = "UI_LFS_1314009986",
    ["Faction disbanded: %s"] = "UI_LFS_1176003958",
    ["Faction name"] = "UI_LFS_1555650816",
    ["Faction owner"] = "UI_LFS_1946330785",
    ["Faction respawn point set."] = "UI_LFS_1338348042",
    ["Faction score"] = "UI_LFS_1950357234",
    ["Faction settings updated."] = "UI_LFS_231430497",
    ["Faction tag"] = "UI_LFS_567749555",
    ["Faction wars are disabled on this server."] = "UI_LFS_391548872",
    ["Factions"] = "UI_LFS_806853516",
    ["Find a faction"] = "UI_LFS_494364890",
    ["Finding a faction (and recruiting)"] = "UI_LFS_414944196",
    ["Getting started"] = "UI_LFS_746069375",
    ["Help"] = "UI_LFS_2089174736",
    ["Hidden"] = "UI_LFS_930551894",
    ["Hide roles"] = "UI_LFS_2146209029",
    ["INVITATIONS"] = "UI_LFS_239688201",
    ["INVITED"] = "UI_LFS_860660811",
    ["Indefinite (until broken)"] = "UI_LFS_1950481143",
    ["Invitation pending"] = "UI_LFS_1803470594",
    ["Invitations"] = "UI_LFS_330363190",
    ["Invite"] = "UI_LFS_976269689",
    ["Invite declined."] = "UI_LFS_1960957985",
    ["Invite for %s revoked."] = "UI_LFS_132351711",
    ["Invite member"] = "UI_LFS_993812969",
    ["Invite sent to %s."] = "UI_LFS_73733979",
    ["Invite-only (players need an invite to join)"] = "UI_LFS_542822083",
    ["Invite-only (players need an invite)"] = "UI_LFS_55386613",
    ["Join an existing faction"] = "UI_LFS_1341541077",
    ["Joined faction: %s"] = "UI_LFS_2144117922",
    ["Kick"] = "UI_LFS_2089286601",
    ["Leader"] = "UI_LFS_1082241975",
    ["Leaderboard"] = "UI_LFS_2009234088",
    ["Leave faction"] = "UI_LFS_559930910",
    ["Left faction: %s"] = "UI_LFS_1111249490",
    ["Left sidebar"] = "UI_LFS_2061129640",
    ["List me"] = "UI_LFS_1532634760",
    ["Loot containers"] = "UI_LFS_312513238",
    ["MEMBERS"] = "UI_LFS_1368406117",
    ["MEMBERSHIP"] = "UI_LFS_1182674873",
    ["Make a Public Area"] = "UI_LFS_1698252277",
    ["Manage claim"] = "UI_LFS_955052777",
    ["Manage members"] = "UI_LFS_440193720",
    ["Manage roles"] = "UI_LFS_972961256",
    ["Members"] = "UI_LFS_512390438",
    ["Message of the day (shown to members on login)"] = "UI_LFS_768799587",
    ["Message with your invite (optional)"] = "UI_LFS_2034335883",
    ["Move / pick up items"] = "UI_LFS_384809738",
    ["My Faction"] = "UI_LFS_1588783364",
    ["My faction & allies"] = "UI_LFS_258953944",
    ["NOT LISTED YET"] = "UI_LFS_250711065",
    ["NOTICE"] = "UI_LFS_1133924748",
    ["Neither side may raid or declare war while active."] = "UI_LFS_1090859605",
    ["No active raid"] = "UI_LFS_640553228",
    ["No active raid."] = "UI_LFS_1810903747",
    ["No description."] = "UI_LFS_209730912",
    ["No faction by that name."] = "UI_LFS_106552048",
    ["No factions exist yet -- create one above."] = "UI_LFS_317712087",
    ["No factions exist yet."] = "UI_LFS_1181132764",
    ["No factions have a claim to raid."] = "UI_LFS_1001683606",
    ["No member by that name."] = "UI_LFS_1328712201",
    ["No other factions exist yet."] = "UI_LFS_416554103",
    ["Nobody has applied to your faction yet."] = "UI_LFS_471189666",
    ["Nobody is advertising for members right now."] = "UI_LFS_1837083250",
    ["Nobody is browsing without an application right now."] = "UI_LFS_1688440798",
    ["Nobody is looking for a faction right now."] = "UI_LFS_171857216",
    ["Non-aggression pacts are disabled on this server."] = "UI_LFS_856623848",
    ["None"] = "UI_LFS_2089401303",
    ["Not in a faction"] = "UI_LFS_1195498853",
    ["Not recruiting"] = "UI_LFS_586361925",
    ["Nothing has happened yet."] = "UI_LFS_1166341815",
    ["Now allied with %s."] = "UI_LFS_240872973",
    ["On-screen feedback & chat"] = "UI_LFS_481194932",
    ["Only our own members."] = "UI_LFS_314021935",
    ["Only the faction owner can change relationships."] = "UI_LFS_1796574462",
    ["Only the faction owner can edit settings."] = "UI_LFS_1284763749",
    ["Only the owner can do that."] = "UI_LFS_830688329",
    ["Only the owner can edit roles."] = "UI_LFS_569677307",
    ["Only when near"] = "UI_LFS_716989716",
    ["Opening an area to outsiders"] = "UI_LFS_960599454",
    ["Optional terms"] = "UI_LFS_2120982315",
    ["Our members plus allied factions' members."] = "UI_LFS_1694197258",
    ["Overview"] = "UI_LFS_1400650379",
    ["Owners must disband, not leave."] = "UI_LFS_2006737657",
    ["PACT"] = "UI_LFS_2089421647",
    ["PLAYSTYLE"] = "UI_LFS_1689024135",
    ["PVP RECORD"] = "UI_LFS_936060043",
    ["Pact proposal declined."] = "UI_LFS_1334848693",
    ["Pick a topic for a detailed guide. Press J any time to open this panel."] = "UI_LFS_393667731",
    ["Private"] = "UI_LFS_596557912",
    ["Propose"] = "UI_LFS_603473029",
    ["Propose Pact"] = "UI_LFS_924403527",
    ["Public"] = "UI_LFS_1257803049",
    ["Put yourself on the recruitment board first."] = "UI_LFS_1544487320",
    ["PvP between members"] = "UI_LFS_43181787",
    ["RECENT EVENTS"] = "UI_LFS_390172778",
    ["REQUEST SENT"] = "UI_LFS_1551271803",
    ["Raid"] = "UI_LFS_2089529639",
    ["Raid another faction's claim"] = "UI_LFS_161615038",
    ["Raid rejected: %s"] = "UI_LFS_279359735",
    ["Raids"] = "UI_LFS_235001498",
    ["Recruit"] = "UI_LFS_516012252",
    ["Recruiting"] = "UI_LFS_411126357",
    ["Relations"] = "UI_LFS_1663414745",
    ["Relationship cleared."] = "UI_LFS_1611525808",
    ["Rename"] = "UI_LFS_1317518498",
    ["Revoke"] = "UI_LFS_1317821174",
    ["Roles & permissions"] = "UI_LFS_1206920641",
    ["SEASON"] = "UI_LFS_1317070995",
    ["Save"] = "UI_LFS_2089566006",
    ["Save pitch"] = "UI_LFS_620391744",
    ["Season"] = "UI_LFS_1356206387",
    ["Seasons & leaderboard"] = "UI_LFS_535330974",
    ["Select a faction on the left."] = "UI_LFS_1172616158",
    ["Server default"] = "UI_LFS_709909146",
    ["Set respawn here"] = "UI_LFS_1075844032",
    ["Set respawn point"] = "UI_LFS_1152952054",
    ["Settings"] = "UI_LFS_184552587",
    ["Share member locations with allies"] = "UI_LFS_1339066040",
    ["Share our claim map with each other"] = "UI_LFS_1881996191",
    ["Share our claims with allies"] = "UI_LFS_284012965",
    ["Share our member locations with each other"] = "UI_LFS_1780862751",
    ["Show all-time"] = "UI_LFS_1923884886",
    ["Show entry banner"] = "UI_LFS_451048578",
    ["Show season"] = "UI_LFS_1417354877",
    ["Shown"] = "UI_LFS_236446134",
    ["Stand inside your claim to set the respawn point."] = "UI_LFS_1434081278",
    ["Stop drawing"] = "UI_LFS_285111462",
    ["Submit claim"] = "UI_LFS_1940099458",
    ["Surrender"] = "UI_LFS_272085587",
    ["TOP CONTRIBUTORS"] = "UI_LFS_888986625",
    ["Tag (short badge)"] = "UI_LFS_1330808944",
    ["Take me off"] = "UI_LFS_1088486589",
    ["Territory"] = "UI_LFS_1088598878",
    ["Territory perks"] = "UI_LFS_411949046",
    ["That didn't work -- see the server log."] = "UI_LFS_1425076884",
    ["That faction is full."] = "UI_LFS_1267240023",
    ["That faction is invite-only. You need an invite to join."] = "UI_LFS_771086516",
    ["That faction isn't recruiting right now."] = "UI_LFS_58947002",
    ["That faction name is taken."] = "UI_LFS_1785618582",
    ["Invalid faction name: %s"] = "UI_LFS_InvalidFactionName",
    ["That player is already in your faction."] = "UI_LFS_1608503757",
    ["That player is no longer online."] = "UI_LFS_InvitePlayerOffline",
    ["That player already belongs to a faction."] = "UI_LFS_InviteTargetHasFaction",
    ["There is already a pending invitation for %s."] = "UI_LFS_InvitePending",
    ["That player declined recently. Wait %s before inviting again."] = "UI_LFS_InviteCooldown",
    ["%s declined your faction invitation."] = "UI_LFS_InviteDeclinedBy",
    ["That player is offline -- they have to be online to join."] = "UI_LFS_23639347",
    ["That role can't be renamed or deleted."] = "UI_LFS_305011581",
    ["That role doesn't exist in your faction."] = "UI_LFS_1428152395",
    ["The recruitment board is disabled on this server."] = "UI_LFS_531687750",
    ["There's no active war to join against them."] = "UI_LFS_690269461",
    ["There's no application from that player."] = "UI_LFS_261598530",
    ["They've already asked to join - accept to add them now, or decline."] = "UI_LFS_1991836314",
    ["This faction has reached its role limit."] = "UI_LFS_104862522",
    ["Top-right corner"] = "UI_LFS_760167280",
    ["Transfer ownership"] = "UI_LFS_99781524",
    ["Unclaim"] = "UI_LFS_447429993",
    ["Unclaim all"] = "UI_LFS_1334101553",
    ["Update listing"] = "UI_LFS_141936469",
    ["Usage: /ff create <name>"] = "UI_LFS_1065311193",
    ["Victory! %s has surrendered the war."] = "UI_LFS_1001345064",
    ["WANTS ALLY"] = "UI_LFS_266933704",
    ["WAR STATUS"] = "UI_LFS_566833063",
    ["War"] = "UI_LFS_193475055",
    ["What do you like doing?"] = "UI_LFS_873038557",
    ["World"] = "UI_LFS_241444271",
    ["YOUR LISTING"] = "UI_LFS_1330209993",
    ["You already have a pact with them."] = "UI_LFS_81381061",
    ["You already own this faction."] = "UI_LFS_1559058552",
    ["You are already at war with them."] = "UI_LFS_1907999797",
    ["You are already in a faction."] = "UI_LFS_565316302",
    ["You are not at war with them."] = "UI_LFS_890004219",
    ["You are not in a faction."] = "UI_LFS_1741979470",
    ["You aren't on the recruitment board."] = "UI_LFS_909397300",
    ["You can only join a war on an ally's side."] = "UI_LFS_1970279532",
    ["You can't declare war on an ally."] = "UI_LFS_1609459129",
    ["You can't join a war against your own ally."] = "UI_LFS_520192313",
    ["You cannot change the owner's role."] = "UI_LFS_589380602",
    ["You cannot kick the owner."] = "UI_LFS_2002642277",
    ["You cannot kick yourself -- use '/ff leave' instead."] = "UI_LFS_237144722",
    ["You don't have permission to do that."] = "UI_LFS_360916176",
    ["You don't have permission to edit claims."] = "UI_LFS_1875652179",
    ["You have no pact with them."] = "UI_LFS_490147665",
    ["You need more personal character score to create a faction (%s points)."] = "UI_LFS_1807345527",
    ["You're already in a faction."] = "UI_LFS_1224306519",
    ["You're already in that war."] = "UI_LFS_759539615",
    ["You're not in a faction."] = "UI_LFS_2113637148",
    ["You're on the recruitment board. Factions can now find you."] = "UI_LFS_1295469920",
    ["You've already applied to that faction."] = "UI_LFS_1798575872",
    ["You've applied to as many factions as you can today."] = "UI_LFS_986248237",
    ["You've been invited to join %s."] = "UI_LFS_1820656528",
    ["You've been taken off the recruitment board."] = "UI_LFS_1696409946",
    ["Your faction has been renamed (it was %s)."] = "UI_LFS_328770793",
    ["Your faction has lost the war against %s."] = "UI_LFS_1506013086",
    ["Your faction is no longer advertising for members."] = "UI_LFS_1503532780",
    ["Your faction is now advertising for members."] = "UI_LFS_1786621912",
    ["Your listing has been updated."] = "UI_LFS_1734155542",
    ["Your own members are never affected by this."] = "UI_LFS_1003018419",
    ["a non-aggression pact protects that faction"] = "UI_LFS_437079111",
    ["areas are too far apart"] = "UI_LFS_998123036",
    ["claim exceeds your faction's size limit"] = "UI_LFS_404810644",
    ["invite-only"] = "UI_LFS_1157034877",
    ["no such faction to raid"] = "UI_LFS_563249056",
    ["no tiles selected"] = "UI_LFS_683985490",
    ["not enough members to claim"] = "UI_LFS_1872559872",
    ["overlaps another faction's claim"] = "UI_LFS_964989599",
    ["raids are disabled on this server"] = "UI_LFS_1787863479",
    ["raids aren't allowed at this hour"] = "UI_LFS_569767701",
    ["selection has too many pieces"] = "UI_LFS_45495042",
    ["that faction has no claim to raid"] = "UI_LFS_50836915",
    ["that faction has no members online to defend"] = "UI_LFS_641328986",
    ["that faction is already under raid"] = "UI_LFS_211438333",
    ["the server blocks claiming in that area"] = "UI_LFS_400222484",
    ["too close to another faction's claim"] = "UI_LFS_1686594084",
    ["too many areas set to Public"] = "UI_LFS_1249873065",
    ["you can't raid an ally"] = "UI_LFS_180045648",
    ["you cannot raid your own faction"] = "UI_LFS_1379567270",
    ["your faction has no raid to call off"] = "UI_LFS_1191522296",
    ["your faction is out of raids for today"] = "UI_LFS_168534403",
    ["Draw a claim area"] = "UI_LFS_DrawClaimArea",
    ["You're not in a faction"] = "UI_LFS_NotInFactionShort",
    ["Faction too small to claim"] = "UI_LFS_FactionTooSmall",
    ["Too many separate areas"] = "UI_LFS_TooManyAreas",
    ["Claim too large for your faction"] = "UI_LFS_ClaimTooLarge",
    ["Overlaps another faction's claim"] = "UI_LFS_ClaimOverlap",
    ["Too far from your other claims"] = "UI_LFS_ClaimTooFar",
    ["Too many public areas"] = "UI_LFS_TooManyPublicAreas",
    ["Too close to another faction's claim"] = "UI_LFS_ClaimTooClose",
    ["Claiming is blocked here"] = "UI_LFS_ClaimBlockedHere",
    ["Claim submitted"] = "UI_LFS_ClaimSubmitted",
    ["FACTION SETTINGS"] = "UI_LFS_FactionSettingsHeader",
    ["IDENTITY"] = "UI_LFS_IdentityHeader",
    ["ACCENT COLOUR"] = "UI_LFS_AccentColourHeader",
    ["OPTIONS"] = "UI_LFS_OptionsHeader",
    ["DANGER ZONE"] = "UI_LFS_DangerZoneHeader",
    ["SIEGE"] = "UI_LFS_SiegeHeader",
    ["HALL OF FAME"] = "UI_LFS_HallOfFameHeader",
    ["Map unavailable -- is PhunZones loaded?"] = "UI_LFS_MapUnavailable",
    ["AT WAR"] = "UI_LFS_AtWar",
    ["PACT OFFER"] = "UI_LFS_1495708531",
    ["PACT SENT"] = "UI_LFS_1216822153",
    ["Your faction is inactive and will be disbanded soon unless a member logs in."] = "UI_LFS_NotifyDecayWarning",
    ["No player by that name. Check the spelling, or pick them from the Recruit tab."] = "UI_LFS_NotifyUnknownPlayer",
    ["That player has asked not to hear from your faction again."] = "UI_LFS_NotifyInviteDeclinedYou",
    ["Your faction has sent all the invites it can today."] = "UI_LFS_NotifyInviteQuota",
    ["%s will no longer see your listing."] = "UI_LFS_NotifyListingHidden",
    ["Raid started on %s. Outnumber the defenders inside and hold to capture."] = "UI_LFS_NotifyRaidStarted",
    ["Your claim is under raid by %s! Get inside and defend it."] = "UI_LFS_NotifyRaidIncoming",
    ["Raid succeeded -- %s's claim is burned and the land is freed."] = "UI_LFS_NotifyRaidWon",
    ["Your claim was captured and burned by %s. The land is now unclaimed."] = "UI_LFS_NotifyRaidLost",
    ["Your raid on %s failed -- they held the line."] = "UI_LFS_NotifyRaidFailed",
    ["You defended your claim against %s's raid."] = "UI_LFS_NotifyRaidDefended",
    ["You called off your raid on %s."] = "UI_LFS_NotifyRaidAbandonedSelf",
    ["%s has called off their raid on your claim."] = "UI_LFS_NotifyRaidAbandoned",
    ["Ownership transferred from %s to %s."] = "UI_LFS_NotifyOwnershipTransferred",
    ["%s is now in the %s role."] = "UI_LFS_NotifyRoleChanged",
    ["%s was removed from the faction."] = "UI_LFS_NotifyMemberKicked",
    ["Role '%s' created."] = "UI_LFS_NotifyRoleCreated",
    ["Role '%s' deleted."] = "UI_LFS_NotifyRoleDeleted",
    ["Role renamed to '%s'."] = "UI_LFS_NotifyRoleRenamed",
    ["Role '%s' updated."] = "UI_LFS_NotifyRoleUpdated",
    ["%s (hostile) has entered your territory!"] = "UI_LFS_NotifyIntrusion",
    ["A ceasefire is in effect -- you can't re-declare war yet."] = "UI_LFS_NotifyCeasefire",
    ["You can't pact a faction you're at war with or hold as an enemy."] = "UI_LFS_NotifyPactHostile",
    ["Pact proposed to %s."] = "UI_LFS_NotifyPactProposed",
    ["%s has proposed a non-aggression pact."] = "UI_LFS_NotifyPactIncoming",
    ["Non-aggression pact formed with %s."] = "UI_LFS_NotifyPactFormed",
    ["You broke your pact with %s."] = "UI_LFS_NotifyPactBrokenSelf",
    ["%s has broken their pact with you!"] = "UI_LFS_NotifyPactBrokenBy",
    ["Your non-aggression pact with %s has expired."] = "UI_LFS_NotifyPactExpired",
    ["A non-aggression pact is in effect -- break it first."] = "UI_LFS_NotifyPactBlocksWar",
    ["You have joined the war against %s."] = "UI_LFS_NotifyJoinedWar",
    ["A non-aggression pact stops you joining a war against them."] = "UI_LFS_NotifyPactBlocksJoin",
    ["A new faction has formed: %s."] = "UI_LFS_EventFactionNew",
    ["The %s faction has disbanded."] = "UI_LFS_EventFactionDisbanded",
    ["The %s faction is now known as %s."] = "UI_LFS_EventFactionRenamed",
    ["The %s faction has faded away from inactivity."] = "UI_LFS_EventFactionDecayed",
    ["%s and %s have formed an alliance."] = "UI_LFS_EventAllianceFormed",
    ["%s has declared war on %s!"] = "UI_LFS_EventWarDeclared",
    ["%s has won its war against %s!"] = "UI_LFS_EventWarWon",
    ["The war between %s and %s has ended."] = "UI_LFS_EventWarEnded",
    ["Season %s is over -- %s takes the crown!"] = "UI_LFS_EventSeasonEnded",
    ["%s and %s have signed a non-aggression pact."] = "UI_LFS_EventPactFormed",
    ["%s has broken its pact with %s."] = "UI_LFS_EventPactBroken",
    ["%s has joined %s's war against %s!"] = "UI_LFS_EventCoalitionJoined",
    ["%s has withdrawn from the war against %s."] = "UI_LFS_EventCoalitionLeft",
    ["Select a member first"] = "UI_LFS_SelectMemberFirst",
    ["Invites can only be revoked"] = "UI_LFS_InviteOnlyRevoke",
    ["Click to withdraw your application."] = "UI_LFS_WithdrawApplicationTooltip",
    ["A line shown to players browsing for a faction."] = "UI_LFS_RecruitPitchTooltip",
    ["Public areas are disabled on this server (MaxPublicClaimAreas = 0)."] = "UI_LFS_PublicAreasDisabled",
    ["Stand inside your claim to set the respawn point"] = "UI_LFS_RespawnInsideClaim",
    ["PvP"] = "UI_LFS_TagPvP",
    ["Builder"] = "UI_LFS_TagBuilder",
    ["Farmer"] = "UI_LFS_TagFarmer",
    ["Medic"] = "UI_LFS_TagMedic",
    ["Driver"] = "UI_LFS_TagDriver",
    ["Scavenger"] = "UI_LFS_TagScavenger",
    ["Any time"] = "UI_LFS_AnyTime",
    ["EU daytime"] = "UI_LFS_EUDaytime",
    ["EU evening"] = "UI_LFS_EUEvening",
    ["NA daytime"] = "UI_LFS_NADaytime",
    ["NA evening"] = "UI_LFS_NAEvening",
    ["APAC"] = "UI_LFS_APAC",
    ["Any size"] = "UI_LFS_AnySize",
    ["Small & tight-knit"] = "UI_LFS_SmallTightKnit",
    ["Large & active"] = "UI_LFS_LargeActive",
    ["unknown"] = "UI_LFS_Unknown",
    ["APPLIED TO JOIN"] = "UI_LFS_AppliedToJoin",
    ["BROWSING - NOT APPLIED"] = "UI_LFS_BrowsingNotApplied",
    ["Invalid claim"] = "UI_LFS_InvalidClaim",
    ["Respawned at faction point"] = "UI_LFS_RespawnedFactionPoint",
    ["This tab failed to draw. See the LasciviousFactionsSystem log."] = "UI_LFS_TabDrawFailed",
    ["Assign role"] = "UI_LFS_AssignRole",
    ["Transfer"] = "UI_LFS_Transfer",
    ["Auto"] = "UI_LFS_Auto",
    ["On"] = "UI_LFS_On",
    ["Off"] = "UI_LFS_Off",
    ["Ally"] = "UI_LFS_Ally",
    ["Enemy"] = "UI_LFS_Enemy",
    ["Neutral"] = "UI_LFS_Neutral",
    ["Accept alliance"] = "UI_LFS_AcceptAlliance",
    ["Accept pact"] = "UI_LFS_AcceptPact",
    ["Break alliance"] = "UI_LFS_BreakAlliance",
    ["Break pact"] = "UI_LFS_BreakPact",
    ["Cancel pact offer"] = "UI_LFS_CancelPactOffer",
    ["Cancel request"] = "UI_LFS_CancelRequest",
    ["Clear (set neutral)"] = "UI_LFS_ClearNeutral",
    ["Declare enemy"] = "UI_LFS_DeclareEnemy",
    ["Declare war"] = "UI_LFS_DeclareWar",
    ["Decline alliance"] = "UI_LFS_DeclineAlliance",
    ["Decline pact"] = "UI_LFS_DeclinePact",
    ["Leave the war"] = "UI_LFS_LeaveWar",
    ["Propose pact"] = "UI_LFS_ProposePact",
    ["Request alliance"] = "UI_LFS_RequestAlliance",
    ["Surrender war"] = "UI_LFS_SurrenderWar",
    ["Invite-only"] = "UI_LFS_InviteOnly",
    ["No other factions yet"] = "UI_LFS_NoOtherFactionsYet",
    ["No other members"] = "UI_LFS_NoOtherMembers",
    ["Invite a player by username:"] = "UI_LFS_InviteUsername",
    ["Options apply immediately. Tag & description need the Save button."] = "UI_LFS_OptionsImmediate",
    ["Your skills and days survived are filled in automatically."] = "UI_LFS_ProfileAutomatic",
    ["Outsiders will be able to alter this area."] = "UI_LFS_OutsidersCanAlter",
    ["This is another faction's claim."] = "UI_LFS_OtherFactionClaim",
    ["Call off your raid? The defender keeps their claim."] = "UI_LFS_AbandonRaidConfirm",
    ["Indefinite, no extra terms."] = "UI_LFS_IndefiniteNoTerms",
    ["not started"] = "UI_LFS_NotStarted",
    ["safe zone"] = "UI_LFS_SafeZone",
    ["this season"] = "UI_LFS_ThisSeason",
    ["all-time"] = "UI_LFS_AllTime",
    ["no one"] = "UI_LFS_NoOne",
    ["indefinite"] = "UI_LFS_Indefinite",
    ["map"] = "UI_LFS_MapTerm",
    ["locations"] = "UI_LFS_LocationsTerm",
    ["(none)"] = "UI_LFS_NoneParenthesized",
    ["(Faction)"] = "UI_LFS_FactionChannel",
    ["(public)"] = "UI_LFS_PublicSuffix",
    ["The owner's role can't be changed"] = "UI_LFS_OwnerRoleLocked",
    ["You can't kick this member"] = "UI_LFS_CannotKickMember",
    ["Remove your faction's claim entirely?"] = "UI_LFS_RemoveAllClaimConfirm",
    ["Disband your faction? This cannot be undone."] = "UI_LFS_DisbandConfirm",
    ["Leave your faction? You'll need an invite to rejoin an invite-only faction."] = "UI_LFS_LeaveConfirm",
    ["Disbanding releases every claim your faction holds and removes all members. This cannot be undone."] = "UI_LFS_DisbandWarning",
    ["Faction Admin"] = "UI_LFS_AdminMenu",
    ["Teleport here"] = "UI_LFS_AdminTeleport",
    ["Remove THIS area"] = "UI_LFS_AdminRemoveArea",
    ["Remove this no-claim zone"] = "UI_LFS_AdminRemoveNoClaim",
    ["Rename this zone..."] = "UI_LFS_AdminRenameZone",
    ["Rename this no-claim zone:"] = "UI_LFS_AdminRenameNoClaimPrompt",
    ["Resize (place Corner A first)"] = "UI_LFS_AdminResizeNeedsCorner",
    ["Clear corner A"] = "UI_LFS_AdminClearCorner",
    ["Block claims here (20x20)..."] = "UI_LFS_AdminBlockHere",
    ["Name this no-claim zone:"] = "UI_LFS_AdminNameNoClaim",
    ["Transfer ownership ->"] = "UI_LFS_AdminTransferOwnership",
    ["Rename..."] = "UI_LFS_RenameEllipsis",
    ["Join mode: open"] = "UI_LFS_AdminJoinOpen",
    ["Join mode: invite-only"] = "UI_LFS_AdminJoinInvite",
    ["List factions (console/chat)"] = "UI_LFS_AdminListFactions",
    ["That command is admin-only."] = "UI_LFS_AdminOnly",
    ["Usage: /ff raid <faction>"] = "UI_LFS_UsageRaid",
    ["Usage: /ff war <faction>"] = "UI_LFS_UsageWar",
    ["Usage: /ff pact <faction>  (proposes, or accepts a pending offer)"] = "UI_LFS_UsagePact",
    ["owner"] = "UI_LFS_RoleOwner",
    ["officer"] = "UI_LFS_RoleOfficer",
    ["member"] = "UI_LFS_RoleMember",
    ["Admin: active faction cleared."] = "UI_LFS_AdminActiveCleared",
    ["Admin: no player."] = "UI_LFS_AdminNoPlayer",
    ["Admin: corner A cleared."] = "UI_LFS_AdminCornerCleared",
    ["uitest: LFS_UiTest.lua did not load."] = "UI_LFS_AdminUiTestMissing",
    ["Admin: no war between those factions."] = "UI_LFS_AdminNoWar",
    ["Admin: war ended."] = "UI_LFS_AdminWarEnded",
    ["Admin: score needs a number."] = "UI_LFS_AdminScoreNeedsNumber",
    ["Admin: no pact between those factions."] = "UI_LFS_AdminNoPact",
    ["Admin: pact cleared."] = "UI_LFS_AdminPactCleared",
    ["Admin: no such member."] = "UI_LFS_AdminNoSuchMember",
    ["Admin: cannot remove the owner (disband instead)."] = "UI_LFS_AdminCannotRemoveOwner",
    ["Admin: bad coordinates."] = "UI_LFS_AdminBadCoordinates",
    ["Admin: both factions must exist."] = "UI_LFS_AdminBothFactionsExist",
    ["Admin: pick two different factions."] = "UI_LFS_AdminDifferentFactions",
    ["Admin: a faction cannot raid itself."] = "UI_LFS_AdminCannotRaidSelf",
    ["Admin: stat must be one of raidsWon, raidsLost, raidsDefended."] = "UI_LFS_AdminInvalidFactionStat",
    ["Admin: count must be a non-zero number."] = "UI_LFS_AdminNonZeroCount",
    ["Admin: a player name is required."] = "UI_LFS_AdminPlayerRequired",
    ["Admin: stat must be 'kills' or 'hours'."] = "UI_LFS_AdminInvalidPlayerStat",
    ["Admin: PhunZones zone data not available."] = "UI_LFS_AdminPhunZonesUnavailable",
    ["Admin: a name is required."] = "UI_LFS_AdminNameRequired",
    ["Admin: season rolled over."] = "UI_LFS_AdminSeasonRolled",
    ["Admin: season clock and baseline reset."] = "UI_LFS_AdminSeasonReset",
    ["No active wars or ceasefires."] = "UI_LFS_ReportNoWars",
    ["No active pacts."] = "UI_LFS_ReportNoPacts",
    ["No factions exist."] = "UI_LFS_NoFactionsExist",
    ["No orphaned faction references."] = "UI_LFS_ReportNoOrphanRefs",
    ["Faction references: nothing orphaned."] = "UI_LFS_ReportNoOrphanFactionRefs",
    ["Nothing was changed. Run /ff admin purge to apply."] = "UI_LFS_ReportPurgeDry",
    ["Claims removed because they overlapped it:"] = "UI_LFS_ReportClaimsRemoved",
    ["No no-claim zones. /ff admin noclaim here [size] to add one."] = "UI_LFS_ReportNoNoClaimZones",
    ["respawn: <not set>"] = "UI_LFS_ReportRespawnUnset",
    ["  claims: re-projected"] = "UI_LFS_ReportClaimsReprojected",
    ["  claims: none"] = "UI_LFS_ReportClaimsNone",
    ["(SeasonsEnabled is OFF)"] = "UI_LFS_ReportSeasonsOff",
    ["Usage: /ff admin create <name> [owner]"] = "UI_LFS_AdminUsageCreate",
    ["Usage: /ff admin addmember <faction> <username> [role]"] = "UI_LFS_AdminUsageAddMember",
    ["Usage: /ff admin claim <faction> <x1> <y1> <x2> <y2>"] = "UI_LFS_AdminUsageClaim",
    ["Usage: /ff admin purge [all|refs|claims|dry]"] = "UI_LFS_AdminUsagePurge",
    ["Usage: /ff admin noclaim zone \"<zone name>\""] = "UI_LFS_AdminUsageNoClaimZone",
}
local function translated(key, fallback, ...)
    if getText then
        local ok, value = pcall(getText, key, ...)
        if ok and value and value ~= key then return value end
    end
    if fallback and select("#", ...) > 0 then
        local ok, value = pcall(string.format, fallback, ...)
        if ok then return value end
    end
    return fallback
end
FF.text = translated
KEYS["Your character score was reset after death."] = "UI_LFS_ScoreResetDeath"
KEYS["Your character score was preserved after death."] = "UI_LFS_ScorePreservedDeath"

-- Server diagnostics and admin tools assemble some lines dynamically. Keep those
-- strings out of the gameplay protocol while still translating them at the final
-- client boundary. Patterns are intentionally anchored so player/faction names are
-- never mistaken for interface text.
local DYNAMIC_PATTERNS = {
    { "UI_LFS_AdminActiveNowMenu", "^Admin: active faction is now '(.+)' %(used by the right%-click menu%)%.$" },
    { "UI_LFS_AdminActiveNow", "^Admin: active faction is now '(.+)'%.$" },
    { "UI_LFS_AdminCornerSet", "^Admin: corner A set at %((%-?%d+),(%-?%d+)%)%. Right%-click the far corner for corner B%.$" },
    { "UI_LFS_AdminNoFaction", "^Admin: no faction '(.+)'%.$" },
    { "UI_LFS_AdminFactionExists", "^Admin: faction '(.+)' already exists%.$" },
    { "UI_LFS_AdminPlayerAlreadyFaction", "^Admin: '(.+)' is already in a faction%.$" },
    { "UI_LFS_AdminPlayerAlreadyIn", "^Admin: '(.+)' is already in (.+)%.$" },
    { "UI_LFS_AdminCreatedFaction", "^Admin: created faction '(.+)' %(owner (.+)%)%.$" },
    { "UI_LFS_AdminDisbandedFaction", "^Admin: disbanded '(.+)'%.$" },
    { "UI_LFS_AdminBadName", "^Admin: bad name %-%- (.+)%.$" },
    { "UI_LFS_AdminAlreadyNamed", "^Admin: '(.+)' is already called that%.$" },
    { "UI_LFS_AdminAlreadyExists", "^Admin: '(.+)' already exists%.$" },
    { "UI_LFS_AdminBeingRaided", "^Admin: '(.+)' is being raided%. End it first %((.+)%)%.$" },
    { "UI_LFS_AdminRaiding", "^Admin: '(.+)' is raiding (.+)%. End it first %((.+)%)%.$" },
    { "UI_LFS_AdminOwnerChanged", "^Admin: (.+) now owns '(.+)' %(was (.+)%)%.$" },
    { "UI_LFS_AdminMemberAdded", "^Admin: added (.+) to '(.+)' %((%d+) members%)%.$" },
    { "UI_LFS_AdminMemberRemoved", "^Admin: removed (.+) from '(.+)'%.$" },
    { "UI_LFS_AdminClaimedHereBlocked", "^Admin: claimed (%d+)x(%d+) at %((%-?%d+),(%-?%d+)%) for '(.+)'%.%s+%(NOTE: inside no%-claim zone '(.+)'%)$" },
    { "UI_LFS_AdminClaimedHere", "^Admin: claimed (%d+)x(%d+) at %((%-?%d+),(%-?%d+)%) for '(.+)'%.$" },
    { "UI_LFS_AdminClaimRectAddedBlocked", "^Admin: added rect %((%-?%d+),(%-?%d+)%)%-%((%-?%d+),(%-?%d+)%) for '(.+)' %((%d+) tiles%)%.%s+%(NOTE: inside no%-claim zone '(.+)'%)$" },
    { "UI_LFS_AdminClaimRectAdded", "^Admin: added rect %((%-?%d+),(%-?%d+)%)%-%((%-?%d+),(%-?%d+)%) for '(.+)' %((%d+) tiles%)%.$" },
    { "UI_LFS_AdminClaimRectSetBlocked", "^Admin: set rect %((%-?%d+),(%-?%d+)%)%-%((%-?%d+),(%-?%d+)%) for '(.+)' %((%d+) tiles%)%.%s+%(NOTE: inside no%-claim zone '(.+)'%)$" },
    { "UI_LFS_AdminClaimRectSet", "^Admin: set rect %((%-?%d+),(%-?%d+)%)%-%((%-?%d+),(%-?%d+)%) for '(.+)' %((%d+) tiles%)%.$" },
    { "UI_LFS_AdminClaimsCleared", "^Admin: cleared claims for '(.+)'%.$" },
    { "UI_LFS_AdminOrphanClaimRemoved", "^Admin: removed orphaned claim zone '(.+)'%.$" },
    { "UI_LFS_AdminNoClaimAt", "^Admin: no claim at %((%-?%d+),(%-?%d+)%)%.$" },
    { "UI_LFS_AdminAllClaimsCleared", "^Admin: cleared all claims for '(.+)'%.$" },
    { "UI_LFS_AdminClaimAreaRemoved", "^Admin: removed one claim area of '(.+)' %((%d+) left%)%.$" },
    { "UI_LFS_AdminRespawnSet", "^Admin: respawn for '(.+)' set to %((%-?%d+),(%-?%d+),(%-?%d+)%)%.$" },
    { "UI_LFS_AdminRelationAlly", "^Admin: (.+) <%-> (.+) set to ally%.$" },
    { "UI_LFS_AdminRelationEnemy", "^Admin: (.+) <%-> (.+) set to enemy%.$" },
    { "UI_LFS_AdminRelationNeutral", "^Admin: (.+) <%-> (.+) set to neutral%.$" },
    { "UI_LFS_AdminNoAttacker", "^Admin: no attacker faction '(.+)'%.$" },
    { "UI_LFS_AdminNoDefender", "^Admin: no defender faction '(.+)'%.$" },
    { "UI_LFS_AdminNoClaimToRaid", "^Admin: '(.+)' has no claim to raid%.$" },
    { "UI_LFS_AdminRaidArmedWarning", "^Admin: armed raid (.+) %-> (.+)%. WARNING: RaidsEnabled is OFF %-%- the tick will not process it%.$" },
    { "UI_LFS_AdminRaidArmed", "^Admin: armed raid (.+) %-> (.+)%.$" },
    { "UI_LFS_AdminRaidSimulationCleared", "^Admin: cleared raid simulation for '(.+)'%.$" },
    { "UI_LFS_AdminRaidSimulation", "^Admin: simulating (%d+) attackers vs (%d+) defenders in '(.+)'%.$" },
    { "UI_LFS_AdminNotUnderRaid", "^Admin: '(.+)' is not under raid%.$" },
    { "UI_LFS_AdminForceCaptured", "^Admin: force%-captured '(.+)'%.$" },
    { "UI_LFS_AdminRaidEnded", "^Admin: ended raid on '(.+)' %(defenders keep the claim%)%.$" },
    { "UI_LFS_AdminForceDecayed", "^Admin: force%-decayed %(disbanded%) '(.+)'%.$" },
    { "UI_LFS_AdminStatChanged", "^Admin: (.+) (%S+) ([%+%-]%d+) %-> (%d+)%.$" },
    { "UI_LFS_AdminWarScore", "^Admin: %+(%d+) war score for (.+) vs (.+)%.$" },
    { "UI_LFS_ReportFactionOwner", "^Faction '(.+)' %(owner=(.+)%)$" },
    { "UI_LFS_ReportFactionStats", "^members=(%d+)%s+score=(%S+)%s+maxTiles=(%S+)%s+claimedTiles=(%S+)$" },
    { "UI_LFS_ReportRoster", "^roster: (.*)$" },
    { "UI_LFS_ReportRespawn", "^respawn: (.+)$" },
    { "UI_LFS_ReportCentroid", "^PhunZones@centroid%((%-?%d+),(%-?%d+)%) %-> (.+) %[(.+)%]$" },
    { "UI_LFS_ReportSafehouses", "^safehouses present: (%d+) / (%d+) rect%(s%) %[(.+)%]$" },
    { "UI_LFS_ReportWar", "^(.+) vs (.+): (%d+) %- (%d+) %(target (%d+)%)(.*)$" },
    { "UI_LFS_ReportCeasefire", "^ceasefire (.+): (%d+)h left$" },
    { "UI_LFS_ReportRenamed", "^Renamed '(.+)' %-> '(.+)'%.$" },
    { "UI_LFS_ReportOrphanCount", "^(%d+) orphaned faction reference%(s%) would be cleared:$" },
    { "UI_LFS_ReportDeadFactions", "^%s+dead factions: (.+)$" },
    { "UI_LFS_ReportRefsCleared", "^Cleared (%d+) reference%(s%) to: (.+)$" },
    { "UI_LFS_ReportClaimsPurged", "^Purged (%d+) orphaned claim zone%(s%)%. See the server log for names%.$" },
    { "UI_LFS_ReportClaimsStripped", "^(.+): removed (%d+) area%(s%), (%d+) left$" },
    { "UI_LFS_AdminNoPhunZoneNamed", "^Admin: no PhunZones zone named '(.+)'%.$" },
    { "UI_LFS_AdminZoneNoGeometry", "^Admin: zone '(.+)' has no usable geometry%.$" },
    { "UI_LFS_AdminNoNoClaimZone", "^Admin: no no%-claim zone '(.+)'%.$" },
    { "UI_LFS_AdminNoClaimZoneRemoved", "^Admin: removed no%-claim zone '(.+)'%.$" },
    { "UI_LFS_AdminNoClaimZoneRenamed", "^Admin: renamed no%-claim zone '(.+)' %-%- '(.+)' is now '(.+)'%.$" },
    { "UI_LFS_AdminNoClaimBlockedRect", "^Admin: blocked claiming in '(.+)' %((.+)%) at %((%-?%d+),(%-?%d+)%)%-%((%-?%d+),(%-?%d+)%)%.$" },
    { "UI_LFS_AdminNoClaimBlockedZone", "^Admin: blocked claiming in zone '(.+)' %((%d+) area%(s%)%)%.$" },
    { "UI_LFS_AdminNoClaimZoneCopy", "^Admin: '(.+)' copies a map zone's geometry %((%d+) area%(s%)%)%. Resize is for hand%-drawn zones %-%- re%-run (.+) to refresh it, or add a new one%.$" },
    { "UI_LFS_AdminNoClaimResized", "^Admin: resized no%-claim zone '(.+)' to %((%-?%d+),(%-?%d+)%)%-%((%-?%d+),(%-?%d+)%)%. Claims inside the area it no longer covers are NOT restored%.$" },
    { "UI_LFS_AdminNoClaimCleared", "^Admin: cleared (%d+) no%-claim zone%(s%)%.$" },
    { "UI_LFS_ReportSeasonNotStarted", "^Season (%d+): not started %(enable %+ wait one tick%)%.$" },
    { "UI_LFS_ReportSeasonTime", "^Season (%d+): (%d+)h left%.$" },
    { "UI_LFS_ReportHandlers", "^command handlers registered:%s+(%d+)$" },
    { "UI_LFS_ReportPhunZonesPresent", "^PhunZones present:%s+(.+)$" },
    { "UI_LFS_ReportZoneLive", "^zone live %[(.+)%]:%s+(.+)$" },
}

function FF.tr(text, ...)
    if type(text) ~= "string" then return text end
    local key = KEYS[text]
    if key then return translated(key, text, ...) end
    local value = text:match("^Invited to (.+)$")
    if value then return translated("UI_LFS_DynamicInvitedTo", text, value) end
    value = text:match("^Under attack by (.+)$")
    if value then return translated("UI_LFS_DynamicUnderAttack", text, value) end
    value = text:match("^Raiding (.+)$")
    if value then return translated("UI_LFS_DynamicRaiding", text, value) end
    value = text:match("^(%d+) online now$")
    if value then return translated("UI_LFS_DynamicOnline", text, value) end
    value = text:match("^Territory (%d+)%% used$")
    if value then return translated("UI_LFS_DynamicTerritoryUsed", text, value) end
    local a, b = text:match("^(%d+) / (%d+) tiles$")
    if a then return translated("UI_LFS_DynamicTiles", text, a, b) end
    local w, h, area = text:match("^Area (%d+) x (%d+) %((%d+) tiles%)$")
    if w then return translated("UI_LFS_DynamicArea", text, w, h, area) end
    value = text:match("^(.+) pts$")
    if value then return translated("UI_LFS_DynamicPoints", text, value) end
    value = text:match("^(.+) tiles$")
    if value then return translated("UI_LFS_DynamicTileCount", text, value) end
    value = text:match("^(%d+) members$")
    if value then return translated("UI_LFS_DynamicMembers", text, value) end
    if text == "1 member" then return translated("UI_LFS_DynamicMemberOne", text) end
    value = text:match("^War %-%- vs (.+)$")
    if value then return translated("UI_LFS_DynamicWarVs", text, value) end
    value = text:match("^first to (%d+)$")
    if value then return translated("UI_LFS_DynamicFirstTo", text, value) end
    value = text:match("^vs (.+)$")
    if value then return translated("UI_LFS_DynamicVs", text, value) end
    value = text:match("^allies: (.+)$")
    if value then return translated("UI_LFS_DynamicAllies", text, value) end
    local d, hr = text:match("^(%d+)d (%d+)h$")
    if d then return translated("UI_LFS_DynamicDaysHours", text, d, hr) end
    local won, lost, defended = text:match("^(%d+) raids won%s+%-%s+(%d+) lost%s+%-%s+(%d+) defended$")
    if won then return translated("UI_LFS_DynamicRaidRecord", text, won, lost, defended) end
    local attacker, defender = text:match("^(.+) attacking (.+)$")
    if attacker then return translated("UI_LFS_DynamicAttacking", text, attacker, defender) end
    local applicants = text:match("^Applicants%s+(%d+)$")
    if applicants then return translated("UI_LFS_DynamicApplicants", text, applicants) end
    local browsing = text:match("^Browsing%s+(%d+)$")
    if browsing then return translated("UI_LFS_DynamicBrowsing", text, browsing) end
    value = text:match("^ROLE: (.+)$")
    if value then return translated("UI_LFS_DynamicRole", text, value) end
    local pactA, pactB, pactDetail = text:match("^(.+) <%-> (.+) %((.+)%)$")
    if pactA then
        local detail = pactDetail
        detail = detail:gsub("indefinite", translated("UI_LFS_Indefinite", "indefinite"))
        local hours = detail:match("^(%d+)h left")
        if hours then
            detail = detail:gsub("^%d+h left", translated("UI_LFS_ReportHoursLeft", "%s h left", hours))
        end
        local shared = pactDetail:match("; shares (.+)$")
        if shared then
            local terms = shared:gsub("map", translated("UI_LFS_MapTerm", "map"))
                :gsub("locations", translated("UI_LFS_LocationsTerm", "locations"))
            local prefix = translated("UI_LFS_ReportShares", "; shares %s", terms)
            detail = detail:gsub("; shares .+$", prefix)
        end
        return translated("UI_LFS_ReportPact", text, pactA, pactB, detail)
    end
    local listName, listOwner, listMembers, listClaims, listExtra =
        text:match("^(.+) owner=(.+) members=(%d+) claims=%[(.*)%](.*)$")
    if listName then
        local attacker, held, need = listExtra:match(" RAID<%-(.+) hold=(%d+)/(%d+)$")
        if attacker then
            listExtra = translated("UI_LFS_ReportRaidSuffix",
                " RAID<-%s hold=%s/%s", attacker, held, need)
        end
        return translated("UI_LFS_ReportFactionList", text,
            listName, listOwner, listMembers, listClaims, listExtra)
    end
    local zoneId, zoneSource, zoneGeometry, zoneName =
        text:match("^(%S+) %[([^%]]+)%] (.-) %-%- (.+)$")
    if zoneId and (zoneSource == "admin" or zoneSource == "zone" or zoneSource == "?") then
        if zoneSource == "admin" then zoneSource = translated("UI_LFS_ReportSourceAdmin", "admin")
        elseif zoneSource == "zone" then zoneSource = translated("UI_LFS_ReportSourceZone", "zone") end
        zoneGeometry = zoneGeometry:gsub("no geometry",
            translated("UI_LFS_ReportNoGeometry", "no geometry"))
        local more = zoneGeometry:match(" %+(%d+) more$")
        if more then
            zoneGeometry = zoneGeometry:gsub(" %+(%d+) more$",
                translated("UI_LFS_ReportMoreAreas", " +%s more", more))
        end
        return translated("UI_LFS_ReportNoClaimLine", text,
            zoneId, zoneSource, zoneGeometry, zoneName)
    end
    for _, entry in ipairs(DYNAMIC_PATTERNS) do
        local captures = { text:match(entry[2]) }
        if captures[1] ~= nil then
            return translated(entry[1], text, unpack(captures))
        end
    end
    return text
end
